"""Migraciones SQL adicionales (columnas y tablas nuevas)."""
from sqlalchemy import text


def run_migrations(conn):
    stmts = [
        "ALTER TABLE subscription_plan ADD COLUMN IF NOT EXISTS price_yearly DOUBLE PRECISION DEFAULT 0",
        "ALTER TABLE subscription_plan ADD COLUMN IF NOT EXISTS stripe_price_id_yearly VARCHAR(120) DEFAULT ''",
        "ALTER TABLE subscription_plan ADD COLUMN IF NOT EXISTS trial_days INTEGER DEFAULT 0",
        "ALTER TABLE subscription_plan ADD COLUMN IF NOT EXISTS stripe_coupon_id VARCHAR(120) DEFAULT ''",
        "ALTER TABLE category ADD COLUMN IF NOT EXISTS required_plan_id INTEGER REFERENCES subscription_plan(id)",
        "ALTER TABLE post ADD COLUMN IF NOT EXISTS is_hidden BOOLEAN DEFAULT FALSE",
        "ALTER TABLE post ADD COLUMN IF NOT EXISTS hidden_reason VARCHAR(300) DEFAULT ''",
        "ALTER TABLE course ADD COLUMN IF NOT EXISTS certificate_enabled BOOLEAN DEFAULT TRUE",
        "ALTER TABLE lesson ADD COLUMN IF NOT EXISTS drip_days INTEGER DEFAULT 0",
        """CREATE TABLE IF NOT EXISTS quiz (
            id SERIAL PRIMARY KEY, section_id INTEGER NOT NULL REFERENCES section(id) ON DELETE CASCADE,
            title VARCHAR(200) NOT NULL, pass_percent INTEGER DEFAULT 70, is_required BOOLEAN DEFAULT TRUE)""",
        """CREATE TABLE IF NOT EXISTS quiz_question (
            id SERIAL PRIMARY KEY, quiz_id INTEGER NOT NULL REFERENCES quiz(id) ON DELETE CASCADE,
            text TEXT NOT NULL, "order" INTEGER DEFAULT 0)""",
        """CREATE TABLE IF NOT EXISTS quiz_option (
            id SERIAL PRIMARY KEY, question_id INTEGER NOT NULL REFERENCES quiz_question(id) ON DELETE CASCADE,
            text VARCHAR(500) NOT NULL, is_correct BOOLEAN DEFAULT FALSE)""",
        """CREATE TABLE IF NOT EXISTS quiz_attempt (
            id SERIAL PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES "user"(id),
            quiz_id INTEGER NOT NULL REFERENCES quiz(id), score INTEGER DEFAULT 0,
            passed BOOLEAN DEFAULT FALSE, created_at TIMESTAMP DEFAULT NOW())""",
        """CREATE TABLE IF NOT EXISTS assignment (
            id SERIAL PRIMARY KEY, section_id INTEGER NOT NULL REFERENCES section(id) ON DELETE CASCADE,
            title VARCHAR(200) NOT NULL, description TEXT DEFAULT '',
            created_at TIMESTAMP DEFAULT NOW())""",
        """CREATE TABLE IF NOT EXISTS assignment_submission (
            id SERIAL PRIMARY KEY, assignment_id INTEGER NOT NULL REFERENCES assignment(id) ON DELETE CASCADE,
            user_id INTEGER NOT NULL REFERENCES "user"(id), content TEXT NOT NULL,
            mentor_feedback TEXT DEFAULT '', status VARCHAR(20) DEFAULT 'pending',
            submitted_at TIMESTAMP DEFAULT NOW(), reviewed_at TIMESTAMP)""",
        """CREATE TABLE IF NOT EXISTS post_report (
            id SERIAL PRIMARY KEY, post_id INTEGER NOT NULL REFERENCES post(id),
            reporter_id INTEGER NOT NULL REFERENCES "user"(id), reason VARCHAR(500) DEFAULT '',
            status VARCHAR(20) DEFAULT 'pending', created_at TIMESTAMP DEFAULT NOW(),
            resolved_at TIMESTAMP)""",
        """CREATE TABLE IF NOT EXISTS live_class_reminder_log (
            id SERIAL PRIMARY KEY, live_class_id INTEGER NOT NULL REFERENCES live_class(id),
            user_id INTEGER NOT NULL REFERENCES "user"(id), reminder_type VARCHAR(10) NOT NULL,
            sent_at TIMESTAMP DEFAULT NOW())""",
        """CREATE TABLE IF NOT EXISTS email_campaign (
            id SERIAL PRIMARY KEY, admin_id INTEGER REFERENCES "user"(id),
            subject VARCHAR(300) NOT NULL, target VARCHAR(30) DEFAULT 'students',
            total_sent INTEGER DEFAULT 0, total_failed INTEGER DEFAULT 0,
            batch_size INTEGER DEFAULT 50, created_at TIMESTAMP DEFAULT NOW())""",
        """CREATE TABLE IF NOT EXISTS course_certificate (
            id SERIAL PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES "user"(id),
            course_id INTEGER NOT NULL REFERENCES course(id),
            certificate_code VARCHAR(32) UNIQUE NOT NULL, issued_at TIMESTAMP DEFAULT NOW())""",
        """CREATE TABLE IF NOT EXISTS live_class_category (
            id SERIAL PRIMARY KEY,
            name VARCHAR(80) UNIQUE NOT NULL,
            color VARCHAR(20) DEFAULT '#7c3aed',
            emoji VARCHAR(10) DEFAULT '📅',
            sort_order INTEGER DEFAULT 0)""",
        "ALTER TABLE live_class ADD COLUMN IF NOT EXISTS category_id INTEGER REFERENCES live_class_category(id)",
        'ALTER TABLE "user" ADD COLUMN IF NOT EXISTS city VARCHAR(120) DEFAULT \'\'',
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS event_reminder_email_subject VARCHAR(300) DEFAULT ''",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS event_reminder_email_body TEXT DEFAULT ''",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS event_reminder_24h_enabled BOOLEAN DEFAULT TRUE",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS event_reminder_1h_enabled BOOLEAN DEFAULT TRUE",
        "ALTER TABLE subscription_plan ADD COLUMN IF NOT EXISTS price_monthly_es DOUBLE PRECISION DEFAULT 0",
        "ALTER TABLE subscription_plan ADD COLUMN IF NOT EXISTS price_monthly_intl DOUBLE PRECISION DEFAULT 0",
        "ALTER TABLE subscription_plan ADD COLUMN IF NOT EXISTS stripe_price_id_es VARCHAR(120) DEFAULT ''",
        "ALTER TABLE subscription_plan ADD COLUMN IF NOT EXISTS stripe_price_id_intl VARCHAR(120) DEFAULT ''",
        'ALTER TABLE "user" ADD COLUMN IF NOT EXISTS whatsapp_vip_pending BOOLEAN DEFAULT FALSE',
        "ALTER TABLE category ADD COLUMN IF NOT EXISTS slug VARCHAR(50) UNIQUE",
        "ALTER TABLE category ADD COLUMN IF NOT EXISTS is_system BOOLEAN DEFAULT FALSE",
        "ALTER TABLE post ADD COLUMN IF NOT EXISTS workflow_status VARCHAR(30)",
        "ALTER TABLE live_class ADD COLUMN IF NOT EXISTS subtopic VARCHAR(200) DEFAULT ''",
        """CREATE TABLE IF NOT EXISTS checkout_intent (
            id SERIAL PRIMARY KEY,
            stripe_session_id VARCHAR(200) UNIQUE,
            plan_id INTEGER NOT NULL REFERENCES subscription_plan(id),
            billing_region VARCHAR(10) DEFAULT 'es',
            customer_email VARCHAR(120) DEFAULT '',
            customer_name VARCHAR(200) DEFAULT '',
            status VARCHAR(20) DEFAULT 'pending',
            user_id INTEGER REFERENCES "user"(id),
            plain_password VARCHAR(80) DEFAULT '',
            created_at TIMESTAMP DEFAULT NOW())""",
        """CREATE TABLE IF NOT EXISTS calendar_month_theme (
            id SERIAL PRIMARY KEY,
            year INTEGER NOT NULL,
            month INTEGER NOT NULL,
            theme_title VARCHAR(200) NOT NULL,
            description TEXT DEFAULT '',
            UNIQUE(year, month))""",
        """CREATE TABLE IF NOT EXISTS library_item (
            id SERIAL PRIMARY KEY,
            title VARCHAR(200) NOT NULL,
            description TEXT DEFAULT '',
            video_url VARCHAR(500) DEFAULT '',
            year INTEGER NOT NULL,
            month INTEGER NOT NULL,
            item_type VARCHAR(20) DEFAULT 'extra',
            live_class_id INTEGER REFERENCES live_class(id),
            sort_order INTEGER DEFAULT 0,
            is_published BOOLEAN DEFAULT TRUE,
            created_at TIMESTAMP DEFAULT NOW())""",
        """CREATE TABLE IF NOT EXISTS resource_tag (
            id SERIAL PRIMARY KEY,
            name VARCHAR(80) UNIQUE NOT NULL)""",
        """CREATE TABLE IF NOT EXISTS resource (
            id SERIAL PRIMARY KEY,
            title VARCHAR(200) NOT NULL,
            description TEXT DEFAULT '',
            media_type VARCHAR(20) DEFAULT 'pdf',
            file_url VARCHAR(500) DEFAULT '',
            file_data BYTEA,
            file_mime VARCHAR(100) DEFAULT '',
            file_name VARCHAR(200) DEFAULT '',
            created_at TIMESTAMP DEFAULT NOW())""",
        """CREATE TABLE IF NOT EXISTS resource_tags (
            resource_id INTEGER NOT NULL REFERENCES resource(id) ON DELETE CASCADE,
            tag_id INTEGER NOT NULL REFERENCES resource_tag(id) ON DELETE CASCADE,
            PRIMARY KEY (resource_id, tag_id))""",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS billing_alert_email_subject VARCHAR(300) DEFAULT ''",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS billing_alert_email_body TEXT DEFAULT ''",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS landing_title VARCHAR(200) DEFAULT ''",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS landing_subtitle TEXT DEFAULT ''",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS landing_benefits TEXT DEFAULT ''",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS landing_hook TEXT DEFAULT ''",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS landing_intro TEXT DEFAULT ''",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS landing_what_is TEXT DEFAULT ''",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS landing_how_helps TEXT DEFAULT ''",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS landing_explore_questions TEXT DEFAULT ''",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS landing_includes TEXT DEFAULT ''",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS landing_for_you TEXT DEFAULT ''",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS landing_closing TEXT DEFAULT ''",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS landing_cta_text VARCHAR(120) DEFAULT ''",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS landing_price_note VARCHAR(200) DEFAULT ''",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS landing_login_title VARCHAR(200) DEFAULT ''",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS landing_login_subtitle VARCHAR(300) DEFAULT ''",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS welcome_video_url VARCHAR(500) DEFAULT ''",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS how_it_works_video_url VARCHAR(500) DEFAULT ''",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS start_page_intro TEXT DEFAULT ''",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS whatsapp_url VARCHAR(500) DEFAULT ''",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS brand_logo_url VARCHAR(500) DEFAULT ''",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS color_primary VARCHAR(20) DEFAULT '#7c3aed'",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS color_secondary VARCHAR(20) DEFAULT '#6d28d9'",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS font_family VARCHAR(120) DEFAULT ''",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS member_of_month_user_id INTEGER REFERENCES \"user\"(id)",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS member_of_month_note VARCHAR(300) DEFAULT ''",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS member_of_month_month VARCHAR(20) DEFAULT ''",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS player_bar_bg VARCHAR(20) DEFAULT '#141414'",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS player_bar_accent VARCHAR(20) DEFAULT ''",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS player_bar_text VARCHAR(20) DEFAULT '#bfbfbf'",
        "ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS player_bar_btn VARCHAR(20) DEFAULT '#2a2a2a'",
    ]
    for sql in stmts:
        try:
            conn.execute(text(sql))
        except Exception:
            pass
